### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [leeeastwood/Haiway#12]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README_Building.md`](https://github.com/leeeastwood/Haiway/blob/05fee3e82941a9f99e84c136fd0659280c4286a0/framework/README_Building.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by LWY931119** [comment]
Hi @bnyf, I send out this [PR](https://github.com/leeeastwood/Haiway/pull/14) to update Homebrew Cask URL, please review it, and merge it into branch master if there are no problems.

**Comment by bnyf** [comment]
> Hi @bnyf, I send out this [PR](https://github.com/leeeastwood/Haiway/pull/14) to update Homebrew Cask URL, please review it, and merge it into branch master if there are no problems.

@LWY931119 Nice work, thanks!
